In [1]:
import os
import pandas as pd
import numpy as np
import pandas as pd
#import seaborn as sns
from matplotlib import pyplot as plt
import zipfile

In [8]:
#import eddypro calculated data
filename = '/home/sreenath/Documents/NOAA/SPLASH/Tower_Data/eddypro_trials/eddypro_jan_feb_23/out/eddypro_adv_full_output_2024-01-26T035152_exp.csv'
flux_eddypro_df = pd.read_csv(filename).drop([0])

In [9]:
flux_eddypro_df

,filename,date,time,DOY,daytime,file_records,used_records,Tau,qc_Tau,rand_err_Tau,...,w/ts_cov,w/co2_cov,w/h2o_cov,w/ch4_cov,w/none_cov,vin_sf_mean,co2_mean,h2o_mean,dew_point_mean,co2_signal_strength_7500_mean
1,2023-01-24T233000_smart3-00565-floor.ghg,2023-01-25,00:00,25,0,18000,18000,-0.0211393,1,-9999,...,-0.0203058,0.00166265,-0.0413785,-9999,-9999,12.5427,402.143,2.11964,-17.7927,89.6536
2,2023-01-25T000000_smart3-00565-floor.ghg,2023-01-25,00:30,25.0208,0,18000,18000,-0.036706,1,-9999,...,-0.0160306,0.00152427,-0.0346783,-9999,-9999,12.54,402.458,2.18953,-17.412,89.6464
3,2023-01-25T003000_smart3-00565-floor.ghg,2023-01-25,01:00,25.0416,0,18000,18000,-0.0604268,1,-9999,...,-0.0289473,0.00266179,0.00707667,-9999,-9999,12.54,402.384,2.20199,-17.3539,89.6435
4,2023-01-25T010000_smart3-00565-floor.ghg,2023-01-25,01:30,25.0624,0,18000,18000,-0.0349191,1,-9999,...,-0.013022,0.00115013,0.0143903,-9999,-9999,12.5453,402.856,2.39779,-16.3356,89.6039
5,2023-01-25T013000_smart3-00565-floor.ghg,2023-01-25,02:00,25.0833,0,18000,18000,-0.0468008,0,-9999,...,-0.0131878,0.00113202,0.048786,-9999,-9999,12.55,402.505,2.30672,-16.7965,89.6278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2023-02-28T220000_smart3-00565-floor.ghg,2023-02-28,22:30,59.9373,0,18000,18000,0.00305658,2,-9999,...,-0.00224222,0.000254069,-0.0335611,-9999,-9999,12.52,408.309,1.64329,-20.8715,89.5493
1679,2023-02-28T223000_smart3-00565-floor.ghg,2023-02-28,23:00,59.9581,0,18000,18000,-0.00965781,1,-9999,...,-0.00783013,0.000753499,-0.0392587,-9999,-9999,12.52,408.082,1.5982,-21.1853,89.5686
1680,2023-02-28T230000_smart3-00565-floor.ghg,2023-02-28,23:30,59.979,0,18000,18000,-0.00232233,2,-9999,...,-0.00526315,0.000576238,-0.0196857,-9999,-9999,12.52,408.729,1.61783,-21.0388,89.6503
1681,2023-02-28T233000_smart3-00565-floor.ghg,2023-03-01,00:00,60,0,18000,18000,0.00587762,1,-9999,...,-0.00918096,0.00109606,-0.0370053,-9999,-9999,12.5286,408.147,1.65462,-20.7911,89.6641
1682,2023-03-01T000000_smart3-00565-floor.ghg,2023-03-01,00:30,60.0208,0,18000,18000,-0.0101775,1,-9999,...,-0.0105062,0.00127049,-0.0131483,-9999,-9999,12.53,407.741,1.76972,-20.0075,89.6712

In [22]:

folder = '/home/sreenath/Documents/NOAA/SPLASH/Tower_Data/eddypro_trials/smartflux_jan_feb_23/3m'
zipfile_list = os.listdir(folder)
zipfile_list.sort()

In [24]:
zipfile_list[0]

'2023-01-24T233000_smart3-00565-floor.zip'

In [33]:
os.chdir(folder)
archive = zipfile.ZipFile(zipfile_list[0], 'r')
csvfile = archive.open('output/eddypro_exp_full_output_2023-01-25T000059_exp.csv')
print(pd.read_csv(csvfile, encoding='utf8', sep=","))

                                  file_info    Unnamed: 1 Unnamed: 2  \
0                                  filename          date       time
1                                       NaN  [yyyy-mm-dd]    [HH:MM]
2  2023-01-24T233000_smart3-00565-floor.ghg    2023-01-25      00:00

  Unnamed: 3   Unnamed: 4    Unnamed: 5    Unnamed: 6  \
0        DOY      daytime  file_records  used_records
1  [ddd.ddd]  [1=daytime]           [#]           [#]
2    25.0000            0         18000         18000

  corrected_fluxes_and_quality_flags Unnamed: 8    Unnamed: 9  ...  \
0                                Tau     qc_Tau  rand_err_Tau  ...
1                       [kg+1m-1s-2]        [#]  [kg+1m-1s-2]  ...
2                      -0.211393E-01          1           NaN  ...

   Unnamed: 172   Unnamed: 173 Unnamed: 174 Unnamed: 175 custom_variables  \
0     w/co2_cov      w/h2o_cov    w/ch4_cov   w/none_cov      vin_sf_mean
1            --             --           --           --               --
2  0.166265E-02  -0.413785E-01          NaN          NaN          12.5427

  Unnamed: 177 Unnamed: 178    Unnamed: 179                   Unnamed: 180  \
0     co2_mean     h2o_mean  dew_point_mean  co2_signal_strength_7500_mean
1           --           --              --                             --
2      402.143      2.11964        -17.7927                        89.6536

  Unnamed: 181
0          NaN
1          NaN
2          NaN

[3 rows x 182 columns]